### ISSUE TITLE
Consider changing package name

### ISSUE THREAD

**Issue by richardsc** [richardsc/mbari#4]
The name `mbari` is pretty vague. A better name might be `bioArgo`.

**Comment by richardsc** [comment]
Two of the (3?) users have voted for `bioArgo`. @dankelley, do you have an opinion on the switch, or on a better package name?

**Comment by dankelley** [comment]
I think bioargo is a good name, if things are general. I think this started out to be a temporary things to read mbari-formatted data, in which case it seemed to make sense then to call it mbari. It's not too clear to me why this doesn't get merged into oce, though.

**Comment by richardsc** [comment]
This has been done as of commit 659e9b513c0b354167556070a7dab587f94ca4ce

Note that the function name has also changed, from `read.argo.mbari()` to `read.bioArgo()`. All documentation and the README.md have been updated.
